import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('pages/home.tsx'),
  route('/annonces', 'pages/annonces.tsx'),
  route('/announces', 'pages/announces.$id.tsx'),
  route('/profile', 'pages/profile.tsx'),
  route('/terms-privacy', 'pages/terms.tsx'),
  route('/logout', 'pages/logout.tsx'),
  route('/logos', 'pages/logos.tsx'),
  route('/transporters', 'pages/transporters.tsx'),
  route('/forgot-password', 'pages/forgot-password.tsx'),
  route('/reset-password', 'pages/reset-password.tsx'),
  route('/help-center', 'pages/help-center.tsx'),
  route('/security-rules', 'pages/security-rules.tsx'),
  route('/assurance-colis', 'pages/assurance-colis.tsx'),
  route('/download-app', 'pages/download-app.tsx'),
  route('/notifications', 'pages/notifications.tsx'),
  route('/stripe-onboarding', 'pages/stripe-onboarding.tsx'),
  route('/support', 'pages/support.tsx'),
  route('/requests/:id/confirm-cancellation', 'pages/request-confirm-cancellation.tsx'),
  route('/requests/:id/dispute-cancellation', 'pages/request-dispute-cancellation.tsx'),
  route('/how-it-work', 'pages/how-it-works.tsx'),
  route('/impact-ecologique', 'pages/ecological-impact.tsx'),
  route('/faq', 'pages/faq.tsx'),
  route('/what-is-happiness', 'pages/what-is-happiness.tsx'),
  route('/become-transporter', 'pages/become-transporter.tsx'),
] satisfies RouteConfig;
